apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-firmware
spec:
  selector:
    matchLabels:
      app: build-firmware
  replicas: 1
  template:
    metadata:
      name: build-firmware
      labels:
        app: build-firmware
    spec:
      containers:
      - name: build-firmware
        image: gcr.io/ultron-cms/build-firmware
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

