apiVersion: batch/v1
kind: Job
metadata:
  name: build-firmware
spec:
  template:
    metadata:
      name: build-firmware
    spec:
      containers:
      - name: build-firmware
        image: gcr.io/ultron-cms/helloworld
        env:
        - name: HELLO_MSG
          value: "Hi James!!!"
      restartPolicy: Never
  backoffLimit: 5
