apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-vol1
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /vol1
    server: 10.203.223.186
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
